### PR TITLE
Change udev user to plugdev

### PR DESCRIPTION
**Pull request by PeterBortas**

### CODE REVIEW

**Comment by PeterBortas** [comment]
s/user/group/

**Comment by JohnDMcMaster** [comment]
There was some talk of changing group from adm to dialout. Is this change related?

**Comment by Elemecca** [comment]
This doesn't change the group assigned to the device. I'm pretty sure what it does change will prevent the rules from matching.

**Comment by Elemecca** [comment]
Also, we should probably add these rules to catch the stock devices:
```
# TL866A / TL866CS stock firmware
SUBSYSTEMS=="usb", ATTRS{idVendor}=="1209", ATTRS{idProduct}=="8661", GROUP="plugdev", MODE="0660"

# TL866II PLUS stock firmware
SUBSYSTEMS=="usb", ATTRS{idVendor}=="a466", ATTRS{idProduct}=="0a53", GROUP="plugdev", MODE="0660"
```

**Comment by PeterBortas** [comment]
This pull request is garbage, I tested this on my dev machine and then walked 2m and managed to type in the wrong thing while copying the change by hand to the machine I was had github credentials on. Closing this. Feel free to make a PR where you clear this up and add the II entry Elemecca.

**Pull request closed without merging**
