### PR TITLE
Add support for the stock bootloader.

### LINKED ISSUE #1: TL866 native bootloader support
Highly desirable to support the original update mechanism so 1) don't need external programmer 2) can go back to original firmware if need be.

This probably involves messing with linker scripts to get code offset past the first page (which has the bootloader). Also need to investigate how to properly apply the encryption table

### PR DESCRIPTION
**Pull request by Elemecca**
The MPLAB X configuration has been updated with the compiler options needed to make the firmware image compatible with the bootloader. The firmware entry point is moved up to 0x1800 and lower addresses are reserved for the bootloader. Another flash region at 0x1fc00 - 0x1ffff is reserved for the bootloader's data tables. The magic number 0x55aaa55a is placed at the end of the image so the bootloader will consider the firmware valid.

Support for reading the serial number block from the bootloader's data tables has been added to the open firmware. The USB string descriptors have been updated to correctly reflect the device including the serial number.

Support for updating the device firmware via the bootloader has been added to the Python client library. It can communicate with the device either via pyusb (libusb or OpenUSB) or with the official Windows driver directly via ctypes. A simple command-line utility `tl866` is provided that can identify the device and update its firmware.

Fixes #1.

### CODE REVIEW

**Comment by Elemecca** [comment]
The update process goes like this:
1. Identify which firmware is running (stock, open, or bootloader).
1. If the bootloader is not running, reset to the bootloader using a method appropriate to the current firmware.
1. Erase and program the device using the bootloader protocol. The firmware is written 64-byte blocks which are encrypted on the fly using model-specific keys.
1. Reset to the new firmware.

## What Works

- Connecting in Python on Linux to any firmware (stock, open, bootloader) via libusb. Needs udev rules for non-root access, but otherwise Just Works&trade;.

- Connecting in Python on Windows to the stock firmware and bootloader via the official Windows driver. Needs the official client software and driver installed. No extra software (e.g. libusb) is needed; talks to the driver through Windows APIs called via ctypes.

- Reset from stock firmware <03.2.85 to bootloader: The Python client can connect, request a report to identify that the stock firmware is running (as opposed to the bootloader), and request a reset to the bootloader.

- Loading the open firmware (or anything else) for flashing from an Intel Hex file.

- Loading the stock firmware for flashing from the `update.dat` file included in the official software.

- Encrypting any firmware image using the appropriate keys for the model and flashing it to the device via the bootloader, assuming Python can connect to the bootloader and load the firmware file.

- Reset from bootloader to any firmware (stock or open).


## What Doesn't Work

- Reset from stock firmware 03.2.85 to bootloader: The reset command that works for earlier versions of the stock firmware does *something*, but afterwards the device is still in the stock firmware, not the bootloader. Needs investigation.

- Reset from open firmware to bootloader. I originally had the open firmware use the stock VID and PID and emulate the stock protocol in the hopes that the official client software could reset it to the bootloader and flash the stock firmware. That worked on Linux with [Radioman's Wine driver][rm-wine], but the official Windows driver crashes if there are any interfaces beyond the first (i.e. the open firmware's CDC interface) so doing it that way isn't really worth the trouble. I've reverted back to the VID and PID assigned to ProgHQ. I need to find a new way to handle this.

[rm-wine]: https://github.com/radiomanV/TL866/tree/master/wine/TL866

## What Hasn't Been Tested

- Anything on OS X.

- Connecting in Python on Windows to any firmware with pyusb (libusb or OpenUSB) with drivers installed via Zadig.

**Comment by Elemecca** [comment]
I've added a command `rb 0000000000` to the open firmware's serial protocol that triggers a reset to bootloader and added a matching `--reset-tty` option to the updater. You can now update when the open firmware is running like so:

```tl866 self update --reset-tty COM6 --stock C:\MiniPro\Update.dat```

That works OK, but I would prefer to find a way to handle the reset to bootloader automatically.

**Comment by Elemecca** [comment]
Per discussion on IRC, the current state of this PR is good enough to review and merge. The few remaining issues can be cleaned up afterwards.

**Comment by JohnDMcMaster** [comment]
One of us will hopefully review this in the next few days. Really looking forward to getting this merged in!

**Comment by cr1901** [comment]
Merging on cnomad's recommendation.

**Pull request merged**
