### PR TITLE
Fixes AClient to work under Windows

### PR DESCRIPTION
**Pull request by RobertBaruch**

### CODE REVIEW

**Comment by RobertBaruch** [comment]
Fixes issues: #66 , #68

**Comment by RobertBaruch** [comment]
Please check that this still works under Linux.

**Comment by RobertBaruch** [comment]
I confirmed that this works under Linux (VMWare instance).

**Comment by JohnDMcMaster** [comment]
Thanks for the patch! We need to test this under Linux before merging

**Comment by JohnDMcMaster** [comment]
Ooops missed that second comment, I think we are good to merge

**Comment by JohnDMcMaster** [comment]
Verified still works under Linux: "python3 examples/blinky.py"

**Comment by JohnDMcMaster** [comment]
Thanks for your patch!

**Comment by cr1901** [comment]
I will close #66 and #68 once I can test on Thursday.

**Pull request merged**
